# PhantomIsolation2 Configuration

# Task settings
task:
  initial-delay-tick: 20
  period-tick: 20

# PhantomIsolation command messages
phantomisolation-command:
  messages:
    status: "&6Phantom Isolation is currently &e%status%"
    enabled-status: "&aenabled"
    disabled-status: "&cdisabled"
    not-player: "&cThis command can only be executed by a player!"
    enabled: "&aPhantom Isolation is now enabled."
    disable: "&cPhantom Isolation is now disabled."
    usage: "&6Usage: /phantomisolation &e[check|disable|enable]"

# PhantomIsolationReload command messages
phantomisolationreload-command:
  messages:
    reload-config: "&aConfiguration reloaded successfully."
    reload-config-error: "&cAn error occurred while reloading the configuration."

# Database error messages
database:
  messages:
    fail-load: "&cFailed to load data from the flat file."
    fail-save: "&cFailed to save data to the flat file."
