# PhantomIsolation2 Configuration

# Task settings
task:
  initial-delay-tick: 20
  period-tick: 20

# PhantomIsolation command messages
phantomisolation-command:
  messages:
    status: "&aPhantom Isolation is currently %status%"
    status_enabled: "&aenabled"
    status_disabled: "&cdisabled"
    not-player: "&cThis command can only be executed by a player!"
    enabled: "&aPhantom Isolation is now enabled."
    disable: "&cPhantom Isolation is now disabled."
    usage: "&6Usage: /phantomisolation &a[check|disable|enable]"
    no-permission: "&You don't have permission to execute this command"

# PhantomIsolationReload command messages
phantomisolationreload-command:
  messages:
    reload-config: "&aConfiguration reloaded successfully."
    reload-config-error: "&cAn error occurred while reloading the configuration."

# Database settings and error messages
database:
  # Database type
  datatype: "flatfile" # Options: "flatfile" or "mysql"

  # MySQL database settings (only used if datatype is "mysql")
  address: "localhost:3306"
  user: "username"
  password: "password"
  database: "phantom_isolation"

  # Flat file error messages
  flatfile-messages:
    fail-load: "&cFailed to load data from the flat file."
    fail-save: "&cFailed to save data to the flat file."

  # MySQL error messages
  mysql-messages:
    fail-connect: "&cFailed to connect to MySQL database."
    fail-load: "&cFailed to load data from the MySQL database."
    fail-save: "&cFailed to save data to the MySQL database."
