name: PhantomIsolation2
version: '${version}'
main: xyz.hynse.phantomisolation2.PhantomIsolation2
api-version: 1.19
folia-supported: true
commands:
  phantomisolation:
    description: Phantom isolation command
    usage: /<command> [check|disable|enable]
    permission: phantomisolation.use
    default: true
    aliases:
      - pil
  phantomisolationreload:
    description: Phantom isolation reload command
    usage: /<command>
    permission: phantomisolation.reload
    default: false
    aliases:
      - pilr
