name: PhantomIsolation2
version: '${version}'
main: xyz.hynse.phantomisolation2.PhantomIsolation2
api-version: 1.19
folia-supported: true
commands:
  phantomisolation:
    usage: /<command> [check|disable|enable]
    aliases:
      - pil
  phantomisolationreload:
    usage: /<command>
    aliases:
      - pilr
permissions:
  phantomisolation.reload:
    description: Phantom isolation reload command
  phantomisolation.use:
    description: Phantom isolation command
    default: true

