name: PhantomIsolation2
version: '${version}'
main: xyz.hynse.phantomisolation2.PhantomIsolation2
api-version: 1.19
folia-supported: true
commands:
  phantomisolation:
    description: Phantom isolation command
    usage: /<command> [check|disable|enable]
  phantomisolationreload:
    description: Phantom isolation reload command
    usage: /<command>
